// aiEngine.js
// The AI Recommendation Engine (flagship module).
//
// If GROQ_API_KEY is set in the environment, real recommendations are
// generated by calling Groq's free, OpenAI-compatible chat completions API
// against the actual emissions data for a company. If no key is set, a
// transparent rule-based fallback runs instead — it's not "AI" in that
// mode, and the API response says so honestly via `source: "rules"` vs
// `source: "groq"`.
//
// Get a free key at https://console.groq.com/keys — no credit card
// required for the free tier at time of writing.

// Default model: openai/gpt-oss-120b — Groq's recommended general-purpose
// reasoning model as of mid-2026 (llama-3.3-70b-versatile, the older
// default, is being deprecated). Override with GROQ_MODEL in .env if you
// want something else — see https://console.groq.com/docs/models for the
// current list.
const MODEL = process.env.GROQ_MODEL || "openai/gpt-oss-120b";

function buildPrompt({ company, kpis, recentLogs, facilities, vehicles }) {
  return `You are the AI Recommendation Engine inside Green Print, a carbon intelligence platform. Analyze this company's real emissions data and produce specific, actionable recommendations — the kind a sustainability consultant would give, not generic advice.

Company: ${company.name} (${company.sector}, ${company.scale}, region: ${company.region})
Facilities: ${facilities.map(f => f.name).join(", ") || "none logged"}
Vehicles: ${vehicles.map(v => v.name).join(", ") || "none logged"}

Current KPIs (computed from this company's region-specific emission factors):
- Total CO2e: ${kpis.co2e} kg
- Electricity-related CO2e: ${kpis.electricityCo2e} kg
- Fuel combustion CO2e: ${kpis.fuelCo2e} kg
- NOx: ${kpis.nox} kg, SOx: ${kpis.sox} kg
- Renewable electricity share: ${kpis.renewableShare}%
- ESG score: ${kpis.esgScore}/100
- Based on ${kpis.sampleSize} logged data points

Recent activity log (most recent first — activity_type is what was consumed, quantity is in the unit shown, renewable_share only applies to electricity entries):
${recentLogs.map(l => `- ${l.timestamp}: ${l.activity_type} — ${l.quantity} ${l.unit}${l.activity_type === "electricity" ? `, ${l.renewable_share}% renewable` : ""}`).join("\n") || "No logs yet."}

Respond with ONLY a JSON object of this exact shape (no markdown fences, no preamble):
{
  "recommendations": [
    {
      "title": "short imperative action, e.g. 'Shift Plant 1 to off-peak hours'",
      "detail": "1-2 sentence explanation grounded in the actual numbers above",
      "expectedSavingPercent": <number 3-25, a realistic estimate>,
      "priority": "high" | "medium" | "low",
      "category": "energy" | "fleet" | "renewable" | "process"
    }
  ]
}
Include 3-5 recommendation objects in the array.`;
}

async function callGroq(prompt) {
  const apiKey = process.env.GROQ_API_KEY;
  const response = await fetch("https://api.groq.com/openai/v1/chat/completions", {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
      Authorization: `Bearer ${apiKey}`
    },
    body: JSON.stringify({
      model: MODEL,
      max_tokens: 1200,
      temperature: 0.4,
      response_format: { type: "json_object" },
      messages: [
        {
          role: "system",
          content:
            "You output ONLY valid JSON. Always respond with a JSON object of the exact shape " +
            '{"recommendations": [ ... ]} and nothing else — no markdown fences, no preamble.'
        },
        { role: "user", content: prompt }
      ]
    })
  });

  if (!response.ok) {
    const errText = await response.text().catch(() => "");
    throw new Error(`Groq API error ${response.status}: ${errText}`);
  }

  const data = await response.json();
  const text = data.choices?.[0]?.message?.content;
  if (!text) throw new Error("No content in Groq response");

  const cleaned = text.replace(/```json|```/g, "").trim();
  const parsed = JSON.parse(cleaned);
  const recommendations = Array.isArray(parsed) ? parsed : parsed.recommendations;
  if (!Array.isArray(recommendations)) {
    throw new Error("Expected a JSON array of recommendations (optionally wrapped in {recommendations: [...]})");
  }
  return recommendations;
}

// Deterministic, explainable fallback — no external calls, no randomness.
// Thresholds are simple and documented so they can be defended, same
// philosophy as the emission factors in emissions.js.
function ruleBasedRecommendations({ kpis, facilities, vehicles }) {
  const recs = [];

  if (kpis.renewableShare < 30) {
    recs.push({
      title: "Increase renewable energy share",
      detail: `Renewable share is ${kpis.renewableShare}%, below the 30% threshold. Sourcing more grid-renewable or on-site solar would directly raise the ESG score.`,
      expectedSavingPercent: 12,
      priority: "high",
      category: "renewable"
    });
  }

  if (kpis.electricityCo2e > kpis.fuelCo2e * 2 && facilities.length > 0) {
    recs.push({
      title: `Audit energy use at ${facilities[0].name}`,
      detail: "Electricity-driven emissions dominate this company's footprint. A facility energy audit (motors, HVAC, idle equipment) typically finds 10-15% avoidable waste.",
      expectedSavingPercent: 10,
      priority: "high",
      category: "energy"
    });
  }

  if (vehicles.length > 0) {
    recs.push({
      title: "Optimize fleet routing",
      detail: `${vehicles.length} vehicle(s) logged. Route consolidation and reduced idle time commonly cut fleet fuel use by 8-15% without new hardware.`,
      expectedSavingPercent: 9,
      priority: "medium",
      category: "fleet"
    });
  }

  if (kpis.esgScore < 60) {
    recs.push({
      title: "Set a quarterly ESG improvement target",
      detail: `Current ESG score is ${kpis.esgScore}/100. Committing to a specific quarterly target (e.g. +5 points) tends to focus facility-level decisions more than the score alone.`,
      expectedSavingPercent: 5,
      priority: "medium",
      category: "process"
    });
  }

  if (recs.length === 0) {
    recs.push({
      title: "Maintain current performance",
      detail: "No urgent thresholds crossed given the data logged so far. Keep logging regularly so trends (not just snapshots) can be analyzed.",
      expectedSavingPercent: 3,
      priority: "low",
      category: "process"
    });
  }

  return recs;
}

// Main entry point. Returns { source, recommendations, generatedAt }.
async function generateRecommendations(context) {
  const hasKey = Boolean(process.env.GROQ_API_KEY);

  if (hasKey) {
    try {
      const prompt = buildPrompt(context);
      const recommendations = await callGroq(prompt);
      return { source: "groq", model: MODEL, recommendations, generatedAt: new Date().toISOString() };
    } catch (err) {
      // Fall through to rules, but surface the failure reason for debugging.
      return {
        source: "rules",
        fallbackReason: err.message,
        recommendations: ruleBasedRecommendations(context),
        generatedAt: new Date().toISOString()
      };
    }
  }

  return {
    source: "rules",
    fallbackReason: "GROQ_API_KEY not set",
    recommendations: ruleBasedRecommendations(context),
    generatedAt: new Date().toISOString()
  };
}

module.exports = { generateRecommendations };
